import { beforeEach, describe, expect, it, vi } from 'vitest';

import { UsageWriter } from '../../../src/core/generator/writers/usage.writer';
import { IrDefinition, IrService } from '../../../src/core/ir/interfaces';

describe('UsageWriter', () => {
  let projectMock: any;
  let sourceFileMock: any;

  const outputDir = '/out';
  const specTitle = 'Test API';
  const specVersion = '1.0.0';

  beforeEach(() => {
    sourceFileMock = {
      getText: vi.fn().mockReturnValue(''),
    };
    projectMock = {
      createSourceFile: vi.fn().mockReturnValue(sourceFileMock),
    };

    vi.clearAllMocks();
  });

  it('should write USAGE.md file to output directory', async () => {
    const ir: IrDefinition = {
      info: { title: specTitle, version: specVersion },
      models: [],
      services: [],
    };

    const writer = new UsageWriter(projectMock, outputDir, specTitle, specVersion);
    await writer.write(ir);

    expect(projectMock.createSourceFile).toHaveBeenCalledWith(
      `${outputDir}/USAGE.md`,
      expect.any(String),
      { overwrite: true },
    );
  });

  it('should include API title and version in header', async () => {
    const ir: IrDefinition = {
      info: { title: specTitle, version: specVersion },
      models: [],
      services: [],
    };

    const writer = new UsageWriter(projectMock, outputDir, specTitle, specVersion);
    await writer.write(ir);

    const generatedContent = projectMock.createSourceFile.mock.calls[0][1];

    expect(generatedContent).toContain('**API:** Test API v1.0.0');
    expect(generatedContent).toContain('Generated by [nog-cli]');
  });

  it('should include generation timestamp', async () => {
    const ir: IrDefinition = {
      info: { title: specTitle, version: specVersion },
      models: [],
      services: [],
    };

    const writer = new UsageWriter(projectMock, outputDir, specTitle, specVersion);
    await writer.write(ir);

    const generatedContent = projectMock.createSourceFile.mock.calls[0][1];

    expect(generatedContent).toMatch(/Generated at: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
  });

  it('should generate service list from IR services', async () => {
    const services: IrService[] = [
      {
        name: 'AuthService',
        operations: new Map(),
      },
      {
        name: 'UsersService',
        operations: new Map(),
      },
      {
        name: 'OrdersService',
        operations: new Map(),
      },
    ];

    const ir: IrDefinition = {
      info: { title: specTitle, version: specVersion },
      models: [],
      services,
    };

    const writer = new UsageWriter(projectMock, outputDir, specTitle, specVersion);
    await writer.write(ir);

    const generatedContent = projectMock.createSourceFile.mock.calls[0][1];

    expect(generatedContent).toContain('`AuthService` - Auth operations');
    expect(generatedContent).toContain('`UsersService` - Users operations');
    expect(generatedContent).toContain('`OrdersService` - Orders operations');
  });

  it('should use tag name as fallback description when service description is missing', async () => {
    const services: IrService[] = [
      {
        name: 'PaymentsService',
        operations: new Map(),
      },
    ];

    const ir: IrDefinition = {
      info: { title: specTitle, version: specVersion },
      models: [],
      services,
    };

    const writer = new UsageWriter(projectMock, outputDir, specTitle, specVersion);
    await writer.write(ir);

    const generatedContent = projectMock.createSourceFile.mock.calls[0][1];

    expect(generatedContent).toContain('`PaymentsService` - Payments operations');
  });

  it('should handle empty services list', async () => {
    const ir: IrDefinition = {
      info: { title: specTitle, version: specVersion },
      models: [],
      services: [],
    };

    const writer = new UsageWriter(projectMock, outputDir, specTitle, specVersion);
    await writer.write(ir);

    const generatedContent = projectMock.createSourceFile.mock.calls[0][1];

    expect(generatedContent).toContain('*(No services generated)*');
  });

  it('should include usage examples with first service name', async () => {
    const services: IrService[] = [
      {
        name: 'AuthService',
        operations: new Map(),
      },
    ];

    const ir: IrDefinition = {
      info: { title: specTitle, version: specVersion },
      models: [],
      services,
    };

    const writer = new UsageWriter(projectMock, outputDir, specTitle, specVersion);
    await writer.write(ir);

    const generatedContent = projectMock.createSourceFile.mock.calls[0][1];

    expect(generatedContent).toContain('import { AuthService }');
    expect(generatedContent).toContain('private readonly authService: AuthService');
    expect(generatedContent).toContain('this.authService.someMethod()');
  });

  it('should include complete usage documentation sections', async () => {
    const ir: IrDefinition = {
      info: { title: specTitle, version: specVersion },
      models: [],
      services: [],
    };

    const writer = new UsageWriter(projectMock, outputDir, specTitle, specVersion);
    await writer.write(ir);

    const generatedContent = projectMock.createSourceFile.mock.calls[0][1];

    expect(generatedContent).toContain('## Quick Start');
    expect(generatedContent).toContain('### Installation');
    expect(generatedContent).toContain('## Usage');
    expect(generatedContent).toContain('### 1. Import the ApiModule in your app module');
    expect(generatedContent).toContain('### 2. Inject services in your controllers/services');
    expect(generatedContent).toContain('### 3. Passing query parameters');
    expect(generatedContent).toContain('## Configuration Options');
    expect(generatedContent).toContain('## Error Handling');
    expect(generatedContent).toContain('### ApiException Helper Methods');
    expect(generatedContent).toContain('### Using with NestJS Exception Filters');
    expect(generatedContent).toContain('## Available Services');
    expect(generatedContent).toContain('## About nog-cli');
  });

  it('should include forRoot() usage warning', async () => {
    const ir: IrDefinition = {
      info: { title: specTitle, version: specVersion },
      models: [],
      services: [],
    };

    const writer = new UsageWriter(projectMock, outputDir, specTitle, specVersion);
    await writer.write(ir);

    const generatedContent = projectMock.createSourceFile.mock.calls[0][1];

    expect(generatedContent).toContain('**⚠️ IMPORTANT:** You MUST use `.forRoot()`');
    expect(generatedContent).toContain('**❌ Common Mistake:**');
    expect(generatedContent).toContain('imports: [ApiModule], // ❌ WRONG - Missing .forRoot()');
  });

  it('should include error handling examples with ApiException', async () => {
    const ir: IrDefinition = {
      info: { title: specTitle, version: specVersion },
      models: [],
      services: [],
    };

    const writer = new UsageWriter(projectMock, outputDir, specTitle, specVersion);
    await writer.write(ir);

    const generatedContent = projectMock.createSourceFile.mock.calls[0][1];

    expect(generatedContent).toContain("import { ApiException } from './api-client/api.exception'");
    expect(generatedContent).toContain('error instanceof ApiException');
    expect(generatedContent).toContain('error.hasStatus(401)');
    expect(generatedContent).toContain('error.is<UnauthorizedError>(401)');
  });

  it('should include nog-cli project links', async () => {
    const ir: IrDefinition = {
      info: { title: specTitle, version: specVersion },
      models: [],
      services: [],
    };

    const writer = new UsageWriter(projectMock, outputDir, specTitle, specVersion);
    await writer.write(ir);

    const generatedContent = projectMock.createSourceFile.mock.calls[0][1];

    expect(generatedContent).toContain('github.com/geckozr/nog-cli');
    expect(generatedContent).toContain('npmjs.com/package/@gecko_zr/nog-cli');
    expect(generatedContent).toContain('npx @gecko_zr/nog-cli generate');
    expect(generatedContent).toContain('Report a bug');
  });

  it('should use default values when spec info is missing', async () => {
    const ir: IrDefinition = {
      models: [],
      services: [],
    };

    const writer = new UsageWriter(projectMock, outputDir, 'Unknown Spec', 'Unknown Version');
    await writer.write(ir);

    const generatedContent = projectMock.createSourceFile.mock.calls[0][1];

    expect(generatedContent).toContain('**API:** Unknown Spec vUnknown Version');
  });
});
