name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue. Please provide detailed information to help us diagnose and fix it quickly.

  - type: input
    id: version
    attributes:
      label: nog-cli Version
      description: The version of nog-cli where you encountered the issue
      placeholder: e.g., 0.9.0
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Output of `node --version`
      placeholder: e.g., v18.17.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: The OS where the issue occurred
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. Run `nog-cli generate ...`
        2. Observe...
        3. Expected...
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs or Output
      description: Paste relevant error messages or CLI output
      render: bash
      placeholder: |
        Error: ...
        Stack trace (if applicable):
        ...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information (OpenAPI spec sample, environment details, etc.)
      placeholder: Add any other context about the problem here

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of nog-cli
          required: false
