/**
 * USAGE.md template for generated SDK documentation.
 * This template contains placeholder variables that will be replaced during generation.
 */
export const USAGE_TEMPLATE = `# API Client Usage Guide

> **API:** {{API_TITLE}} v{{API_VERSION}}

> Generated by [nog-cli](https://github.com/geckozr/nog-cli) - NestJS OpenAPI Generator CLI  
> Generated at: {{TIMESTAMP}}  
> nog-cli version: {{NOGCLI_VERSION}}

This directory contains the auto-generated NestJS HTTP client for your OpenAPI specification.

## Quick Start

### Installation

Install the required peer dependencies in your NestJS project:

\`\`\`bash
npm install @nestjs/common @nestjs/axios axios rxjs class-validator class-transformer
\`\`\`

These files are ready to be imported directly into your NestJS application.

## Usage

### 1. Import the ApiModule in your app module

**⚠️ IMPORTANT:** You MUST use \`.forRoot()\` to import the module, not just \`ApiModule\` alone.

\`\`\`typescript
import { Module } from '@nestjs/common';
import { ApiModule } from './api-client/api.module';

@Module({
  imports: [
    // ✅ CORRECT - Use forRoot() with configuration
    ApiModule.forRoot({
      baseUrl: 'https://api.example.com',
      headers: {
        'X-Api-Key': 'your-api-key',
      },
    }),
  ],
})
export class AppModule {}
\`\`\`

**❌ Common Mistake:** Don't import like this:
\`\`\`typescript
@Module({
  imports: [ApiModule], // ❌ WRONG - Missing .forRoot()
})
\`\`\`

This will cause dependency injection errors like:
\`\`\`
Error: Nest can't resolve dependencies of the YourService (?)
\`\`\`

### 2. Inject services in your controllers/services

\`\`\`typescript
import { Injectable } from '@nestjs/common';
import { {{FIRST_SERVICE}} } from './api-client/services/{{FIRST_SERVICE_FILE}}.service';

@Injectable()
export class MyService {
  constructor(private readonly {{FIRST_SERVICE_CAMEL}}: {{FIRST_SERVICE}}) {}

  async example() {
    // Use the service methods
    const result = await this.{{FIRST_SERVICE_CAMEL}}.someMethod();
    return result;
  }
}
\`\`\`

### 3. Passing query parameters

Methods with query parameters use an inline object type for better DX:

\`\`\`typescript
// ✅ Only pass the parameters you need
const users = await usersService.searchUsers({
  fields: ['id', 'name', 'email'],
  groups: ['members'],
  pageSize: 20,
});

// ✅ Parameters are optional - pass none if you want defaults
const allUsers = await usersService.searchUsers();

// ✅ IDE autocomplete and JSDoc for each parameter
const results = await usersService.searchUsers({
  keywords: 'john',      // <- Hover for description
  orderBy: 'createdAt',  // <- Type-safe enum values
});
\`\`\`

## Configuration Options

The \`ApiModuleConfig\` interface accepts:

- \`baseUrl\` (required): Base URL for all API requests
- \`headers\` (optional): Default headers included in all requests
- \`httpOptions\` (optional): Additional Axios configuration options

## Error Handling

The generated services throw \`ApiException<T>\` for HTTP errors, where \`T\` is the typed error response from your OpenAPI spec:

\`\`\`typescript
import { ApiException } from './api-client/api.exception';
import { UnauthorizedError } from './api-client/models/UnauthorizedError';
import { NotFoundError } from './api-client/models/NotFoundError';

try {
  const result = await {{FIRST_SERVICE_CAMEL}}.getCurrentAuth();
} catch (error) {
  if (error instanceof ApiException) {
    console.log('Status:', error.status);
    console.log('Error data:', error.data);

    // Use helper methods for cleaner code
    if (error.hasStatus(401)) {
      const unauthorizedError = error.data as UnauthorizedError;
      console.log('Error code:', unauthorizedError.code);
    }

    if (error.hasStatus(404)) {
      const notFoundError = error.data as NotFoundError;
      console.log('Entity type:', notFoundError.entityType);
    }

    // Or use the is() helper to check and cast in one step
    if (error.is<UnauthorizedError>(401)) {
      console.log('Unauthorized:', error.data.code);
    }
  }
}
\`\`\`

### ApiException Helper Methods

- \`hasStatus(status)\` - Check if the exception has a specific HTTP status code
- \`is<T>(status)\` - Type guard that checks status and narrows the type of \`data\` to \`T\`

\`\`\`typescript
// hasStatus() - simple status check
if (error.hasStatus(401, 403)) {
  console.log('Authentication or authorization error');
}

// is<T>() - status check with type narrowing
if (error.is<NotFoundError>(404)) {
  // error.data is now typed as NotFoundError
  console.log('Entity not found:', error.data.entityType);
}
\`\`\`

### Using with NestJS Exception Filters

You can create a global filter to convert \`ApiException\` to NestJS exceptions:

\`\`\`typescript
import { ExceptionFilter, Catch, ArgumentsHost, HttpException } from '@nestjs/common';
import { ApiException } from './api-client/api.exception';

@Catch(ApiException)
export class ApiExceptionFilter implements ExceptionFilter {
  catch(exception: ApiException, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse();

    response.status(exception.status).json({
      statusCode: exception.status,
      message: exception.message,
      error: exception.data,
    });
  }
}
\`\`\`

## Available Services

The following services are available based on your OpenAPI tags:

{{SERVICES_LIST}}

Check the individual service files for available methods.

---

## About nog-cli

This client was generated using **nog-cli** (NestJS OpenAPI Generator CLI).

- 🔗 **GitHub**: [github.com/geckozr/nog-cli](https://github.com/geckozr/nog-cli)
- 📦 **npm**: [npmjs.com/package/@gecko_zr/nog-cli](https://www.npmjs.com/package/@gecko_zr/nog-cli)
- 🐛 **Issues**: [Report a bug](https://github.com/geckozr/nog-cli/issues)
- ❤️ **Sponsor**: [Support this project](https://github.com/sponsors/geckozr)

### Generate your own SDK

\`\`\`bash
# Use without installing
npx @gecko_zr/nog-cli generate ./your-openapi.json -o ./generated

# Or install globally
npm install -g @gecko_zr/nog-cli
nog-cli generate ./your-openapi.json -o ./generated
\`\`\`
`;
